Dev Final version for testing
digitalearthafrica/deafrica-airflow pull request #120
Opened 2021-03-09 03:41 UTC by carioca-au

- Make the process works with 1 message per time
- removed unnecessary functions

2021-03-09 04:33 UTC, pindge approved these changes

2021-03-09 04:42 UTC, alexgleith requested changes

2021-03-09 04:42 UTC, alexgleith commented on dags/landsat-scenes-sync/README.md
> +Dags to read, either in bulk or daily, stacs released by USGS and migrate to Africa's servers
```suggestion
Dags to identify USGS Collection 2 Landsat scenes either in bulk or per-day, push them onto a queue, and then to copy the data to Cape Town and upgrade the STAC metadata and create a notification.
```

2021-03-09 04:42 UTC, alexgleith commented on dags/landsat-scenes-sync/README.md
> +  * This Dag will start a Python process which will download GZ files, which are split per landsat and collection, from USGS
```suggestion
  * This Dag will start a Python process which will download per-satellite tar.gz files from USGS'
```

2021-03-09 04:42 UTC, alexgleith commented on dags/landsat-scenes-sync/README.md
> +    file server, send the stac, in bulk, to our SQS queue in Africa.
```suggestion
    file server, send the STAC documents in bulk to our SQS queue in Africa. 
```

2021-03-09 04:42 UTC, alexgleith commented on dags/landsat-scenes-sync/README.md
> +    send the stac to our SQS queue in Africa.
```suggestion
  * This Dag will start a Python process which will access the USGS API, accordingly to informed dates, and 
    send the STAC documents to our SQS queue in Africa.
```

2021-03-09 04:42 UTC, alexgleith commented on dags/landsat-scenes-sync/README.md
> +    After that sending to an SNS topic.
```suggestion
  * This Dag will be started by the scheduler to pull messages from the SQS queue, validate the message, process 
    the message adding missing items, changing links to point to our S3 bucket and transforming from stac 0.7 to 1.0. 
    After that it sends the STAC document to an SNS topic.
```

2021-03-09 04:42 UTC, alexgleith commented on dags/landsat-scenes-sync/README.md
> +    filled automatically by the SNS, and will process by Datacube.
```suggestion
  * This Dag will be started by the scheduler to pull the messages from a second SQS queue, which is 
    filled automatically by the SNS, and will indexed into the Datacube.  
```

2021-03-09 04:42 UTC, alexgleith commented on dags/landsat-scenes-sync/README.md
> +    pip install --user stactools[all] && pip install --user pystac && pip install --user
```suggestion
    pip install --user stactools[all] pystac
```

2021-03-09 04:42 UTC, alexgleith commented on dags/utils/url_request_utils.py
> +
???

2021-03-09 23:57 UTC, carioca-au commented on dags/landsat-scenes-sync/README.md
> +Dags to read, either in bulk or daily, stacs released by USGS and migrate to Africa's servers
Done

2021-03-09 23:57 UTC, carioca-au commented on dags/landsat-scenes-sync/README.md
> +  * This Dag will start a Python process which will download GZ files, which are split per landsat and collection, from USGS
Done

2021-03-09 23:57 UTC, carioca-au commented on dags/landsat-scenes-sync/README.md
> +    After that sending to an SNS topic.
Done

2021-03-09 23:57 UTC, carioca-au commented on dags/landsat-scenes-sync/README.md
> +    pip install --user stactools[all] && pip install --user pystac && pip install --user
Done

2021-03-09 23:57 UTC, carioca-au commented on dags/utils/url_request_utils.py
> +
Removed

2021-03-10 00:05 UTC, alexgleith approved these changes

2021-03-10 05:02 UTC, merged